import { Fugaz_One, Open_Sans, Rubik_Wet_Paint } from 'next/font/google';
import './globals.css';
import Navbar from './(components)/Navbar';
import { AuthProvider } from '@/context/Authcontext';

const opensans = Open_Sans({ subsets: ['latin'] });
const fugaz = Fugaz_One({ subsets: ['latin'], weight: ['400'] });
const rubik = Rubik_Wet_Paint({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: 'emmax',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const header = <header className="pt-3"></header>;
  const footer = (
    <footer
      className={
        'capitalize fixed bottom-0 left-0 w-full text-center py-3 bg-gradient-to-r from-orange-900 to-gray-900 text-orange-600  ' +
        fugaz.className
      }
    >
      <p>© {new Date().getFullYear()} emmax. All rights reserved.</p>
    </footer>
  );

  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={
            'w-full mx-auto text-base bg-gradient-to-r from-gray-800 to-orange-900 min-h-screen flex flex-col ' +
            opensans.className
          }
        >
          {header}
          <main className="flex-grow mb-16">{children}</main>
          {footer}
        </body>
      </AuthProvider>
    </html>
  );
}
